### ISSUE TITLE
[improvement] Related Threads in the contact sidebar looks too bright

### ISSUE THREAD

**Issue by LukeXuan** [jackiehluo/n1-material#2]
``` html
  <div name="unsafe-component-wrapper" style="order:99;" data-reactid=".4.0.0:$RelatedThreads">
```

I really love this theme, but the div above is too bright for me, compared to the whole application. Would please you choose a more harmonious colour for it? Thanks.

**Comment by jackiehluo** [comment]
@LukeXuan Whoops, didn't get a notification for this issue! Yeah, sure. Probably also a fix for the contact sidebar, since it should be using `ui-variables` for that.

**Comment by jackiehluo** [comment]
By the way, pushed that change a few days ago!
